
from random import randint, seed

rq1 = []
rq2 = []

my_seed = config['seed'] if 'seed' in config else 3124
seed(my_seed)

for i in range(30):
    rq1.append(randint(1, 8))
    rq2.append(randint(1, 64))

rule all:
    input:
        expand("analysis/cdf/map_{rq1}-{rq2}.png", zip, rq1 = rq1, rq2 = rq2),
        "analysis/cdf/map_all.png"

rule model:
    input:
        "bin/nuevomatchup/ranges-test.txt"
    output:
        "analysis/model/map_{rq1}-{rq2}.txt"
    shell:
        "bin/nuevomatchup/bin/util-rqrmi64.exe --file {input} --custom-rqrmi 1,{wildcards.rq1},{wildcards.rq2} --print-map {output}"

rule cdf_one:
    input:
        "analysis/model/map_{rq1}-{rq2}.txt"
    output:
        png = "analysis/cdf/map_{rq1}-{rq2}.png",
        txt = "analysis/cdf/map_{rq1}-{rq2}.txt"
    script:
        "scripts/cdf.py"

rule cdf_all:
    input:
        expand("analysis/model/map_{rq1}-{rq2}.txt", zip, rq1 = rq1, rq2 = rq2)
    output:
        png = "analysis/cdf/map_all.png",
        txt = "analysis/cdf/map_all.txt"
    script:
        "scripts/cdf.py"
